version: '3'

tasks:
  typescript:
    dir: frontend
    sources:
      - ./src/**/*.ts
      - ./src/**/*.tsx
    cmds:
      - npx tsc

  dev:
    desc: Start frontend in development mode
    dir: frontend
    cmds:
      - npx vite

  build:
    desc: Build frontend for production
    dir: frontend
    sources:
      - ./src/**/*.ts
      - ./src/**/*.tsx
    deps:
      - typescript
    cmds:
      - npx vite build

  test:unit:
    desc: Run frontend unit tests
    dir: frontend
    sources:
      - ./src/**/*.ts
      - ./src/**/*.tsx
      - ./tests/**/*.ts
      - ./tests/**/*.tsx
      - vitest.frontend.ts
    cmds:
      - npx vitest run -c vitest.frontend.ts --dir tests {{.CLI_ARGS}}

  test:watch:
    desc: Watch for frontend unit tests
    dir: frontend
    cmds:
      - npx vitest watch -c vitest.frontend.ts --dir tests {{.CLI_ARGS}}
