version: '3'

services:
  db:
    image: 'postgres:14'
    ports:
      - '54320:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
