version: '3'

services:
  db:
    image: 'postgres:14'
    ports:
      - '54320:5432'
    environment:
      POSTGRES_USER: expense-tracker
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: expense_tracker
