version: '3'

tasks:
  install:
    sources:
      - package.json
      - yarn.lock
    generates:
      - node_modules
    cmds:
      - yarn --frozen-lockfile --prefer-offline

  format:
    deps:
      - install
    cmds:
      - npx prettier --write {{.FILES | default "."}}
    vars:
      FILES:
        sh: git diff --name-only HEAD | xargs

  lint:
    deps:
      - install
    cmds:
      - npx prettier --check {{.FILES | default "."}}
    vars:
      FILES:
        sh: git diff --name-only HEAD | xargs

  test:
    deps:
      - install
    cmds:
      - npx vitest run

  test-watch:
    deps:
      - install
    cmds:
      - npx vitest watch

  mutation:
    deps:
      - install
    sources:
      - backend/**/*.ts
      - lib/**/*.ts
      - stryker.conf.mjs
    cmds:
      - npx stryker run

  start:
    desc: Start the backend server for production
    deps:
      - install
    dir: backend
    env:
      NODE_ENV: production
    cmds:
      - npx esno server.ts

  dev:
    desc: Start the backend server for development
    deps:
      - install
    dir: backend
    env:
      NODE_ENV: development
    cmds:
      - npx esno watch server.ts
