version: '3'

env:
  API_HOST: 0.0.0.0
  API_LOG_LEVEL: info
  API_PORT: 54321
  DB_CLIENT: pg
  DB_DATABASE: expense_tracker
  DB_HOST: localhost
  DB_PASSWORD: secret
  DB_PORT: 54320
  DB_USER: expense_tracker
  DB_VERSION: 14
  REDIS_URL: redis://localhost:63790

tasks:
  install:
    sources:
      - package.json
      - yarn.lock
    generates:
      - node_modules
    cmds:
      - yarn --frozen-lockfile --prefer-offline

  tsc:
    sources:
      - backend/**/*.ts
      - lib/**/*.ts
      - tsconfig.json
    generates:
      - dist
    cmds:
      - npx tsc

  docker:
    cmds:
      - docker-compose up -d

  format:
    cmds:
      - npx prettier --write .

  lint:
    cmds:
      - npx prettier --check .

  test:
    cmds:
      - task: test:unit
      - task: test:integration
      - task: test:mutation

  test:unit:
    sources:
      - backend/src/**/*.ts
      - backend/tests/**/*.ts
      - vitest.config.ts
    cmds:
      - npx vitest --dir backend/tests/unit {{.CLI_ARGS}}

  test:integration:
    sources:
      - backend/src/**/*.ts
      - backend/tests/**/*.ts
      - vitest.config.ts
    cmds:
      - npx vitest --dir backend/tests/integration {{.CLI_ARGS}}

  test:mutation:
    cmds:
      - npx stryker run

  start:
    desc: Start the backend server for production
    dir: backend
    env:
      NODE_ENV: production
    cmds:
      - npx esno server.ts

  dev:
    desc: Start the backend server for development
    dir: backend
    env:
      NODE_ENV: development
    cmds:
      - npx esno watch server.ts

  migration:create:
    desc: Create a new database migration
    dir: backend
    cmds:
      - npx typeorm migration:create ./migrations/{{.CLI_ARGS}}

  migration:run:
    desc: Run all pending migrations
    deps:
      - tsc
    dir: dist/backend
    cmds:
      - npx typeorm migration:run -d config.js

  migration:revert:
    desc: Rollback latest migration
    deps:
      - tsc
    dir: dist/backend
    cmds:
      - npx typeorm migration:revert -d config.js
