version: '3'

tasks:
  install:
    sources:
      - package.json
      - yarn.lock
    generates:
      - node_modules
    cmds:
      - yarn --frozen-lockfile --prefer-offline

  format:
    deps:
      - install
    cmds:
      - npx prettier --write .

  lint:
    deps:
      - install
    cmds:
      - npx prettier --check .

  test:
    deps:
      - install
    sources:
      - backend/**/*.ts
    cmds:
      - npx vitest --changed HEAD~1

  mutation:
    deps:
      - install
    sources:
      - backend/**/*.ts
      - stryker.conf.mjs
    cmds:
      - npx stryker run

  start:
    desc: Start the backend server for production
    deps:
      - install
    dir: backend
    env:
      NODE_ENV: production
    cmds:
      - npx esno server.ts

  dev:
    desc: Start the backend server for development
    deps:
      - install
    dir: backend
    env:
      NODE_ENV: development
    cmds:
      - npx esno watch server.ts
