version: '3'

env:
  API_HOST: 0.0.0.0
  API_LOG_LEVEL: info
  API_PORT: 54321
  DB_CLIENT: pg
  DB_DATABASE: expense_tracker
  DB_HOST: localhost
  DB_PASSWORD: secret
  DB_PORT: 54320
  DB_USER: expense_tracker
  DB_VERSION: 14

tasks:
  install:
    sources:
      - package.json
      - yarn.lock
    generates:
      - node_modules
    cmds:
      - yarn --frozen-lockfile --prefer-offline

  docker:
    cmds:
      - docker-compose up -d

  format:
    deps:
      - install
    cmds:
      - npx prettier --write .

  lint:
    deps:
      - install
    cmds:
      - npx prettier --check .

  test:
    cmds:
      - task: test:unit
      - task: test:integration

  test:unit:
    deps:
      - install
    sources:
      - backend/src/**/*.ts
      - backend/tests/**/*.ts
      - vitest.config.ts
    cmds:
      - npx vitest run --dir backend/tests/unit

  test:integration:
    deps:
      - install
      - docker
    sources:
      - backend/src/**/*.ts
      - backend/tests/**/*.ts
      - vitest.config.ts
    cmds:
      - npx vitest run --dir backend/tests/integration

  test:mutation:
    deps:
      - install
      - docker
    cmds:
      - npx stryker run

  start:
    desc: Start the backend server for production
    deps:
      - install
      - docker
    dir: backend
    env:
      NODE_ENV: production
    cmds:
      - npx esno server.ts

  dev:
    desc: Start the backend server for development
    deps:
      - install
      - docker
    dir: backend
    env:
      NODE_ENV: development
    cmds:
      - npx esno watch server.ts
