version: '3'

env:
  API_HOST: 0.0.0.0
  API_LOG_LEVEL: info
  API_PORT: 54321
  DB_CLIENT: pg
  DB_DATABASE: expense_tracker
  DB_HOST: localhost
  DB_PASSWORD: secret
  DB_PORT: 54320
  DB_USER: expense_tracker
  DB_VERSION: 14
  REDIS_URL: redis://localhost:63790

includes:
  backend: ./backend

tasks:
  install:
    desc: Install dependencies
    sources:
      - package.json
      - backend/package.json
      - frontend/package.json
      - yarn.lock
    generates:
      - node_modules
    cmds:
      - yarn install --frozen-lockfile --prefer-offline

  format:
    desc: Format codebase
    cmds:
      - npx prettier --write .

  lint:
    desc: Lint codebase
    cmds:
      - npx prettier --check .

  docker:
    desc: Start Docker services
    dir: backend
    cmds:
      - docker-compose up -d

  test:
    desc: Run acceptance tests
    cmds:
      - task: backend:test:unit
      - task: backend:test:integration
      - task: backend:test:mutation
